### ISSUE TITLE
AttributeError: 'DatabaseWrapper' object has no attribute 'encoding'

### ISSUE THREAD

**Issue by bsadecki** [lionheart/django-pyodbc#85]
I used @WilliamQLiu's great wiki entry to get started. I'm passing all of the test checkpoints along the way tsql, isql, etc. I was getting this error for a long time:

```
[unixODBC][FreeTDS][SQL Server]Unable to connect to data source
```

Finally resolved that but now I'm getting the following on runserver:

```
System check identified no issues (0 silenced).
Unhandled exception in thread started by <function wrapper at 0x107fa32a8>
Traceback (most recent call last):
  File "/Users/mac_user/.virtualenvs/django_env/lib/python2.7/site-packages/django/utils/autoreload.py", line 222, in wrapper
    fn(*args, **kwargs)
  File "/Users/mac_user/.virtualenvs/django_env/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 107, in inner_run
    self.check_migrations()
  File "/Users/mac_user/.virtualenvs/django_env/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 159, in check_migrations
    executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
  File "/Users/mac_user/.virtualenvs/django_env/lib/python2.7/site-packages/django/db/migrations/executor.py", line 17, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/Users/mac_user/.virtualenvs/django_env/lib/python2.7/site-packages/django/db/migrations/loader.py", line 48, in __init__
    self.build_graph()
  File "/Users/mac_user/.virtualenvs/django_env/lib/python2.7/site-packages/django/db/migrations/loader.py", line 183, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/Users/mac_user/.virtualenvs/django_env/lib/python2.7/site-packages/django/db/migrations/recorder.py", line 59, in applied_migrations
    self.ensure_schema()
  File "/Users/mac_user/.virtualenvs/django_env/lib/python2.7/site-packages/django/db/migrations/recorder.py", line 49, in ensure_schema
    if self.Migration._meta.db_table in self.connection.introspection.get_table_list(self.connection.cursor()):
  File "/Users/mac_user/.virtualenvs/django_env/lib/python2.7/site-packages/django/db/backends/__init__.py", line 165, in cursor
    cursor = self.make_debug_cursor(self._cursor())
  File "/Users/mac_user/.virtualenvs/django_env/lib/python2.7/site-packages/django_pyodbc/base.py", line 293, in _cursor
    if not self.ops.is_db2:
  File "/Users/mac_user/.virtualenvs/django_env/lib/python2.7/site-packages/django_pyodbc/operations.py", line 32, in is_db2
    cur = self.connection.cursor()
  File "/Users/mac_user/.virtualenvs/django_env/lib/python2.7/site-packages/django/db/backends/__init__.py", line 165, in cursor
    cursor = self.make_debug_cursor(self._cursor())
  File "/Users/mac_user/.virtualenvs/django_env/lib/python2.7/site-packages/django_pyodbc/base.py", line 334, in _cursor
    return CursorWrapper(cursor, self.driver_supports_utf8, self.encoding)
AttributeError: 'DatabaseWrapper' object has no attribute 'encoding'
```

I'm running:

```
Django (1.7.7)
django-pyodbc (0.2.8)
pyodbc (3.0.9)
```

**Comment by RossRogers** [comment]
Please start by debugging your pyodbc connection as that is a dependency on django-pyodbc.  Something like:

    import pyodbc
    driver_name = 'IBM i Access ODBC Driver'
    if os.name == 'nt':
        driver_name = 'iSeries Access ODBC Driver'
    connection = pyodbc.connect("CONNTYPE=2;DRIVER={%s};SYSTEM=192.168.1.2;UID=rrogers;PWD=foobar"%driver_name)
    cursor = connection.cursor()
    cursor.execute('select 1')
