### ISSUE TITLE
using slices breaks placeholders.

### ISSUE THREAD

**Issue by vegitron** [lionheart/django-pyodbc#90]
Using the syntax described at https://docs.djangoproject.com/en/1.8/topics/db/queries/#limiting-querysets, I am getting this SQL error:

```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/pmichaud/django/sqlshare-rest/local/lib/python2.7/site-packages/django/db/models/query.py", line 71, in __repr__
    data = list(self[:REPR_OUTPUT_SIZE + 1])
  File "/home/pmichaud/django/sqlshare-rest/local/lib/python2.7/site-packages/django/db/models/query.py", line 96, in __iter__
    self._fetch_all()
  File "/home/pmichaud/django/sqlshare-rest/local/lib/python2.7/site-packages/django/db/models/query.py", line 854, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/home/pmichaud/django/sqlshare-rest/local/lib/python2.7/site-packages/django/db/models/query.py", line 220, in iterator
    for row in compiler.results_iter():
  File "/home/pmichaud/django/sqlshare-rest/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 710, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/home/pmichaud/django/sqlshare-rest/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 781, in execute_sql
    cursor.execute(sql, params)
  File "/home/pmichaud/django/sqlshare-rest/local/lib/python2.7/site-packages/django/db/backends/util.py", line 69, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/pmichaud/django/sqlshare-rest/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/home/pmichaud/django/sqlshare-rest/local/lib/python2.7/site-packages/django_pyodbc/base.py", line 429, in execute
    raise utils.DatabaseError(*e.args)
DatabaseError: ('The SQL contains 0 parameter markers, but 1 parameters were supplied', 'HY000')
```

Here's a class + usage that demos the problem:

```python
from django.db import models 
class Demo(models.Model):                                                                                    
    num = models.IntegerField()  
```

```
(sqlshare-rest)pmichaud@anise:~/django/sqlshare-rest$ DB=MSSQL python manage.py shell
Python 2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from sqlshare_rest.models import Demo
>>> q1 = Demo.objects.filter(num=4)
>>> q1.query.sql_with_params()
(u'SELECT [sqlshare_rest_demo].[id], [sqlshare_rest_demo].[num] FROM [sqlshare_rest_demo] WHERE [sqlshare_rest_demo].[num] = %s ', (4,))
>>> q2 = q1[1:2]
>>> q2.query.sql_with_params()
('SELECT _row_num, [id], [num] FROM ( SELECT ROW_NUMBER() OVER ( ORDER BY [AAAA].[id] ASC) as _row_num, [AAAA].[id], [AAAA].[num] FROM ( SELECT [sqlshare_rest_demo].[id], [sqlshare_rest_demo].[num] FROM [sqlshare_rest_demo] WHERE [sqlshare_rest_demo].[num] = {} ) AS [AAAA]) as QQQ where 1 < _row_num and _row_num <= 2', (4,))
>>> q3 = q1[:2]
>>> q3.query.sql_with_params()
(u'SELECT TOP 2 [sqlshare_rest_demo].[id], [sqlshare_rest_demo].[num] FROM [sqlshare_rest_demo] WHERE [sqlshare_rest_demo].[num] = %s ', (4,))
>>> 
```

You'll notice the query for q1 and q3 has %s, but q2 has {}.

**Comment by vegitron** [comment]
This happens in django_pyodbc/compiler.py , line 388:

from_clause % parens

which translates  [sqlshare_rest_demo].[num] = %s  and an empty dictionary into [sqlshare_rest_demo].[num]  = <string representation of an empty dictionary, aka {} >

**Comment by vegitron** [comment]
This was caused by where clauses with only 1 constraint not being wrapped in ().  Pull request #91 addresses this by replacing any remaining %s statements with _placeholder_{i} values.

**Comment by dlo** [comment]
@vegitron Thank you for the PR! Just started reviewing. This is awesome. Really appreciate you contributing.

**Comment by vegitron** [comment]
Closing, since PR #91 has been merged.
